#!/bin/sh

case "$1" in
    start)
        echo "Loading kernel modules..."
        /usr/bin/scull_load || exit 1
        /usr/bin/module_load faulty || exit 1
        modprobe hello || exit 1
        ;;
    stop)
        echo "Stopping kernel modules..."
        # Unload modules if needed
        /usr/bin/scull_unload || exit 1
        /usr/bin/module_unload faulty || exit 1
        rmmod hello || exit 1
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0

